### ISSUE TITLE
GigyaSDK symbolic link points to unknown target

### ISSUE THREAD

**Issue by skwakman** [gigya/cordova-plugin-gigya#2]
Since commit https://github.com/gigya/cordova-plugin-gigya/commit/d8f6f1e5703cf5eaf735a9bc14ba98bc25981268 , the symbolic link `src/ios/libs/GigyaSDK.framework/GigyaSDK` seems to be pointing to an unknown target. My (macOS) terminal lists the file as such:
`GigyaSDK -> ????`

The previous commit did have a working symbolic link, pointing towards a file in the `Versions` subdirectory which no longer exists on `master`.

**Comment by denis-mitin** [comment]
Library structure was changed according to Apple requirements to support App Thinning.
Please, tell me if there are issues with the library..

**Comment by skwakman** [comment]
Because of this issue, I cannot build and run ios Cordova apps using GigyaSDK anymore. 

During plugin installation (as part of `cordova prepare`) I get the following error message:
`cp: no such file or directory: <my cordova project dir>/plugins/cordova-plugin-gigya/src/ios/libs/GigyaSDK.framework/GigyaSDK`

And during build (using `cordova build ios`) the build process quits with this error:
`ld: framework not found GigyaSDK`

**Comment by denis-mitin** [comment]
I restored previous version of GigyaSDK.framework.
Pls, try now, cordova prepare should work.

**Comment by skwakman** [comment]
Just tried it, it works again! Thanks!

**Comment by denis-mitin** [comment]
Thank you for the feedback and sorry for inconvenience.

**Comment by skwakman** [comment]
bug fixed, closing issue. Thanks again!
