### ISSUE TITLE
Android google login "Operation canceled" after selecting account

### ISSUE THREAD

**Issue by kpfecteau** [gigya/cordova-plugin-gigya#5]
Hello, currently on android (test device is 5.1) when the google plus login modal opens and an account is selected the gigyaClient.loginToProvider returns Operation canceled

```
gigyaClient.loginToProvider('googleplus')
     .then(function(response) {
          console.log("RESPONSE: ", response);
     })
     .catch(function(error) {
          console.log("ERROR: ", error);
     });
```

and the output is:
```
{
  data: Object
  errorCode: 200001
  errorDetails: undefined
  errorMessage: "Operation canceled"
}
```

**Comment by VictorNavarro31** [comment]
Hi @kpfecteau 

When you sign a APK and then ask Google for a OAuth2 token, you have to register your signed app through the dev console. It's a security measure based on the app package name and the sha1 fingerprint. To do that, you have to : 

1 Sign your APK, manually or through Gradle or whatever: the Android documentation is pretty clear on this step.

2 Get your sha1 fingerprint; as mention in this SO answer, it's kind of easy on Android Studio: in the Gradle panel, select the signingReport task under your root project and run it - the SHA1 fingerprint will show in the text output.

3 Register your APK through the Google dev console: create a new Credentials / OAuth client id / Android, defined by the SHA1 fingerprint you got and your APK package name.

Please review this info, it should fix your issue.

**Comment by kpfecteau** [comment]
Thank you for the super quick reply!  Looks like the debug apk wasn't setup in the build.json with the proper keystore.
